FROM iestriana/lamp
MAINTAINER Alejandro

RUN apt-get -y update
RUN apt-get -y upgrade
ADD inicioservicio.sh /usr/bin/
ADD carga.sql /usr/bin
RUN apt -y install net-tools
#Instacion wordpress
RUN apt-get install -y git
WORKDIR /var/www/html/
RUN rm -rf index.html
RUN echo "<?php header("Location: ./PROYECTO_IAW_ROMAN_CABALLERO/")?>" > index.php
RUN git clone https://github.com/Alejandro314/PROYECTO_IAW_ROMAN_CABALLERO.git
RUN chown -R www-data:www-data /var/www/html/PROYECTO_IAW_ROMAN_CABALLERO/
EXPOSE 80/udp
EXPOSE 80/tcp
EXPOSE 3306/tcp
RUN timedatectl set-timezone UTC
RUN dpkg-reconfigure tzdata
#Iniciar sevicios
RUN chmod 755 /usr/bin/inicioservicio.sh
CMD /usr/bin/inicioservicio.sh


