Vagrant.configure("2") do |config|

#Máquina1 
  config.vm.define "name1" do |m1|
    m1.vm.box = "ubuntu/trusty64"
  end
#Máquina2
  config.vm.define "name2" do |m2|
    m2.vm.box = "ubuntu/xenial64"
  end
end

